### ISSUE TITLE
größe des DEP Exportes

### ISSUE THREAD

**Issue by samuel4711** [a-sit-plus/at-registrierkassen-mustercode#140]
Hallo, 
wie groß darf die Datei zum Überprüfen werden ?
Habe dem Tool mal eine 5 MB Datei zum abarbeiten gegeben, das wurde jedoch mit einer Exception quittiert.

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Unknown Source)
        at java.lang.String.<init>(Unknown Source)
        at java.lang.StringBuilder.toString(Unknown Source)
        at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:356)
        at com.fasterxml.jackson.core.io.SegmentedStringWriter.getAndClear(SegmentedStringWriter.java:83)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1007)
        at at.asitplus.regkassen.verification.common.rpc.RKObjectMapper.stringify(Unknown Source)
        at at.asitplus.regkassen.verification.common.data.VerificationResult.toString(Unknown Source)
        at java.lang.String.valueOf(Unknown Source)
        at java.lang.StringBuilder.append(Unknown Source)
        at at.asitplus.regkassen.verification.common.BaseVerificationModule.afterVerify(Unknown Source)
        at at.asitplus.regkassen.verification.common.BaseVerificationModule.verifySingle(Unknown Source)
        at at.asitplus.regkassen.verification.common.BaseVerificationModule.verifySingle(Unknown Source)
        at at.asitplus.regkassen.verification.cmdline.CheckSingleReceipt.checkReceipt(CheckSingleReceipt.java:224)
        at at.asitplus.regkassen.verification.cmdline.CheckDEPExportFormat.main(CheckDEPExportFormat.java:155)

**Comment by areiter** [comment]
Sie brauchen der Java VM nur mehr heap space zu gestehen, der Aufruf schaut dann ca. wie folgt aus:
`java -jar -Xmx2048m...`

**Comment by samuel4711** [comment]
hat geklappt ... danke
