### ISSUE TITLE
DEP Prüftool OutOfMemoryError

### ISSUE THREAD

**Issue by andix25** [a-sit-plus/at-registrierkassen-mustercode#158]
Beim Prüfen von DEP-Exports von Testkunden (mehrere tausend Einträge) stürzt das Prüftool immer ab.

```
Machine readable code validation # 2604: PASS

Fatal internal error. Detailed error-stacktrace:

java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Unknown Source)
        at java.lang.String.<init>(Unknown Source)
        at java.lang.StringBuilder.toString(Unknown Source)
        at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:356)
        at com.fasterxml.jackson.core.io.SegmentedStringWriter.getAndClear(SegmentedStringWriter.java:83)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1007)
        at at.asitplus.regkassen.verification.common.rpc.RKObjectMapper.stringify(Unknown Source)
        at at.asitplus.regkassen.verification.common.data.VerificationResult.toString(Unknown Source)
        at java.lang.String.valueOf(Unknown Source)
        at java.lang.StringBuilder.append(Unknown Source)
        at at.asitplus.regkassen.verification.common.BaseVerificationModule.afterVerify(Unknown Source)
        at at.asitplus.regkassen.verification.common.BaseVerificationModule.verifySingle(Unknown Source)
        at at.asitplus.regkassen.verification.common.BaseVerificationModule.verifySingle(Unknown Source)
        at at.asitplus.regkassen.verification.cmdline.Prueftool.checkReceipt(Prueftool.java:244)
        at at.asitplus.regkassen.verification.cmdline.CheckDEPExportFormat.performSingleReceiptCheck(CheckDEPExportFormat.java:316)
        at at.asitplus.regkassen.verification.cmdline.CheckDEPExportFormat.main(CheckDEPExportFormat.java:76)
```

**Comment by ErichFreitag** [comment]
Schauen sie mal auf https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/140.

**Comment by andix25** [comment]
Ja stimmt, in Kombination mit einer 64-bit JVM klappt es auch. Habe aber schnell mal einen Speicherverbrauch von einigen Gigabyte. Nicht optimal, aber okay...

**Comment by asitplus-pteufl** [comment]
Optimierung wird in späteren Versionen durchgeführt, bei V1.0.0 war der Fokus darauf die Qualität der Überprüfungen auf Produktionsniveau zu bringen. 
Im Moment werden die Ergebnisse der Einzelbelege für die nachfolgende DEP-Prüfung im Speicher gehalten, daher der hohe Verbrauch.
