### ISSUE TITLE
Problems with running "regkassen-demo-0.5.jar"

### ISSUE THREAD

**Issue by slavok1** [a-sit-plus/at-registrierkassen-mustercode#27]
After running the "regkassen-demo-0.5.jar" there is problem with generating the AES256 encryption value of Transaction counter ("Stand-Umsatz-Zaehler-AES256-ICM"). In "qr-code-rep.txt" file there are "null" value for this field, just for Training and Storno receipt they are OK, as there is different calculation. Also "ocr-code-rep.txt" file is empty etc.

After compilation the project and debugging the files I found the problem occur in "AESutil.java" file on the line 268 "cipher.init(Cipher.ENCRYPT_MODE, symmetricKey, ivSpec);"

the result for every no training receipt is 
-------------------------------------------------------------------------------------------
java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.init(Cipher.java:1393)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at at.asitplus.regkassen.core.base.util.AESUtil.encryptCTR(AESUtil.java:268)
	at at.asitplus.regkassen.core.DemoCashBox.updateTurnOverCounterAndAddToDataToBeSigned(DemoCashBox.java:335)
	at at.asitplus.regkassen.core.DemoCashBox.prepareSignatureData(DemoCashBox.java:215)
	at at.asitplus.regkassen.core.DemoCashBox.createStoreAndSignReceiptPackage(DemoCashBox.java:79)
	at at.asitplus.regkassen.core.DemoCashBox.storeReceipt(DemoCashBox.java:141)
	at at.asitplus.regkassen.demo.SimpleDemo.main(SimpleDemo.java:189)

-------------------------------------------------------------------------------------------------------------------
Could you help with this problem?

**Comment by pteufl** [comment]
sure, the unlimited strength policy files are missing. they are required for the AES256 key. you can download them from oracle for your respective jvm.

**Comment by slavok1** [comment]
thank you for advice

**Comment by MarkusWET** [comment]
Woran könnte es noch liegen, dass man den exakt gleichen Fehler wie slavok1 erhält, wenn man den Sourcecode selbst kompiliert & ausführt? Die beiden Policy-JARs wurden bereits in den lib/security Ordner des Projekt-SDKs kopiert und mehr sollte ja auch nicht nötig sein (abgesehen vom ebenfalls durchgeführten Neustart der IDE).

**Comment by MarkusWET** [comment]
Nevermind, hab es tatsächlich einfach nur falsch kopiert...
