### ISSUE TITLE
Testtools out of memory

### ISSUE THREAD

**Issue by xmasmc** [a-sit-plus/at-registrierkassen-mustercode#313]
Habe das Problem, dass das Testtool V1.0.0 bei dem Versuch ein DEP mit 2626 Einträgen zu testen die Fehlermeldung **java.lang.OutOfMemoryError**: Java heap space ausgibt und daher nicht korrekt arbeitet.
Gibt es ein bekanntes Limit ?

Bei 1250 Einträgen funktioniert das Tool. Bei 1500 Einträgen nicht mehr.

**Java Version:**
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
Java HotSpot(TM) Client VM (build 25.66-b18, mixed mode)

**Betriebssystem:**
Win7 prof. 64bit

**Aufruf des Testprogramms und Ausgabe:**
call java -jar D:\download\Registrierkassen\A-Sit\v1.0\regkassen-demo-1.0.0\regkassen-verification-depformat
-1.0.0.jar -i xmas_dep.json   -c cryptographicMaterialContainer.json -o .  1>testdep_out.txt
java.lang.OutOfMemoryError: Java heap space
        at com.fasterxml.jackson.core.util.TextBuffer.carr(TextBuffer.java:739)
        at com.fasterxml.jackson.core.util.TextBuffer.expand(TextBuffer.java:700)
        at com.fasterxml.jackson.core.util.TextBuffer.append(TextBuffer.java:463)
        at com.fasterxml.jackson.core.io.SegmentedStringWriter.write(SegmentedStringWriter.java:58)
        at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._flushBuffer(WriterBasedJsonGenerator.java:1880)
        at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._writePPFieldName(WriterBasedJsonGenerator.java:306)
        at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._writeFieldName(WriterBasedJsonGenerator.java:157)
        at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeFieldName(WriterBasedJsonGenerator.java:122)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:670)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1428)
        at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1129)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1001)
        at at.asitplus.regkassen.verification.common.rpc.RKObjectMapper.stringify(Unknown Source)
        at at.asitplus.regkassen.verification.cmdline.CheckDEPExportFormat.main(CheckDEPExportFormat.java:109)

**Comment by ckvsoft** [comment]
Servas X
Versuch den heapsize zu erhöhen.  Früher oder später ist es aber wieder aus. Ich glaub so irgendwo bei 3.8 Gigabyte. 

java -Xmx512M -Xms64M  -jar D:\download\Registrierkassen\A-Sit\v1.0\regkassen-demo-1.0.0\regkassen-verification-depformat
-1.0.0.jar -i xmas_dep.json -c cryptographicMaterialContainer.json -o . 1>testdep_out.txt

LG chris

**Comment by xmasmc** [comment]
Hi Chris,
vielen Dank, funktioniert mit 1750 Einträgen, aber bei 2600 Einträgen leider auch nicht.
Wäre schön wenn das Testtool auch viel größere DEP prüfen könnte.
Danke für die Hilfe

**Comment by ckvsoft** [comment]
😊 Ich hab nur 1000 getestet.  Bin dann davon ausgegangen wenn die funktionieren wird wohl meine Routine zum erstellen richtig sein. Wobei man weiß ja nie. Ich hatte ja das Problem das die ersten 10 Ok waren und danach alle falsch. Hat aber am padding gelegen. Du kannst das sicher noch raufdrehen nur irgendwann ist wieder aus. Dazu müsste das Tool etwas abgeändert werden. Nur genau kennen ich mich mit Java auch nicht aus. Wäre interessant wenn ein finanzbeamter einen Fehler mit seinem Test Tool hat. Wer dann wohl in Beweisnot steht?

**Comment by senton82** [comment]
Hi,

eventuell hilft es auch eine 64bit JDK zum Anwerfen des Verification-Tools zu verwenden - da gibt es dann das 3,8GB Limit nicht und mit entsprechender Heapsize habe ich schon DEPs mit mehreren tausend Einträgen getestet.

HTH
Stefan

**Comment by xmasmc** [comment]
Hi Stefan,
vielen Dank für den Tipp, werde das Testen.
ANMERKUNG
Wenn meine Reg,kassen Software die selbe Qualität hat, wie das Testtool, dann muss ich dem Finanzbeamten, welcher das DEP exportiert haben möchte, leider sagen, dass mehr als ca. 2000 DEP Einträge nicht möglich sind, da mein Reg.kassen Software auf einem 32 Bit System läuft ...........

**Comment by senton82** [comment]
Hi,

ich glaube @asitplus-pteufl hat einmal angekündigt, dass in neueren Versionen des Verification-Tools auf Speicheroptimierung geachtet wird - ich nehme an, dass intern einfach sehr viele Daten zwischengespeichert werden.

Wir verwenden als Backend eine MySQL-Datenbank - auch ich hatte kurz bedenken, wie sich ein Export über lange Zeiträume darauf auswirkt. Wenn man allerdings nur die wirklich notwendigen Daten aus dem DEP für das JSON-Format queried (bei uns liegt das dann noch dazu in einer Table, daher können wir uns hier teurer Joins sparen) habe ich gute Erfahrungen mit tausenden von Einträgen gemacht. Aber ich stimme zu, dass dies bei langen Betriebszeiten sicher interessant wird :-)

LG,
Stefan

**Comment by asitplus-pteufl** [comment]
Die aktuelle Version des Prüftools hat (wie auf der Starseite angemerkt) das Problem, das alle Daten zwischengespeichert werden. Der Speicherverbrauch wird in der nächsten Version optimiert und bleibt dann im Wesentlichen konstant (da immer nur ein paar Belege geprüft werden).
Auskunft zum Release-Datum der nächsten Version kann ich als A-SIT Plus nicht geben, bitte beim BMF anfragen.

**Comment by Josma** [comment]
Liegt wohl in erster Linie daran, das immer alle Belegnummer mitgespeichert werden... (wegen dem Vergleich, ob eindeutig)
ich schaffe nur 984. habe aber relativ lange Belegnummer.
Cool wäre es, wenn man im Prüftool sagen könnte prüfe alles ausser Belegnummern. ich weiß, das diese eindeutig sind... Sonst hätten wir auch bereits vor dem DEp probleme bekommen ;-)

Nein, im Ernst. Es gibt zumindest bei uns einfach Kassenfälle die nur alle paar Wochen gemacht werden. ich kann das mit dem Prüftool jetzt nicht wirklich testen... da schon jetzt schluss ist...

Und mittendrinnen kann ich die Prüfung nicht starten, weil dann das Tool sofort aufhört, weil der Startbeleg fehlt... ich frage mich wie die Finanzer das eigentlich prüfen...
