### ISSUE TITLE
Frage bezüglich Ausführen des Prüftools

### ISSUE THREAD

**Issue by Skerge12** [a-sit-plus/at-registrierkassen-mustercode#327]
Guten Tag,
es tut mir leid dass ich schon wieder fragen muss aber mit Java hab ich leider überhaupt keine Erfahrung.

Ich möchte das Prüftool ausführen um meinen DEP Export zu testen.

Leider bekomme ich immer eine Fehlermeldung:
Error while parsing the input files. Detailed error-stacktrace:
java.io.IOException: RKSV_DEP_EXPORT file C:\Registrierkasse\DEP_Export.csv does not exist.
Exiting.
at at.asitplus.regkassen.verification.cmdline.Prueftool.parseDEP(Prueftool.java:162)
at at.asitplus.regkassen.verification.cmdline.Prueftool.parseDEPInput(Prueftool.java:146)
at at.asitplus.regkassen.verification.cmdline.CheckDEPExportFormat.main(CheckDEPExportformat.java:61)

Ich verstehe auch nicht warum das Prüftool eine Datei "DEP_Export.csv) verlangt.
Bei den übergebenen Parametern für das Prüftool habe ich andere Dateibezeichnungen eingeben.

Das ist der Programmaufruf:
"C:\Program Files"\Java\jre1.8.0_121\bin\java -jar  "Z:\Java_Code_Registrierkassenbeispiele\regkassen-demo-1.0.0\regkassen-verification-receipts-1.0.0.jar" -v -f -i "Z:\Kassa-LB1_DEP_Export_Gesamt.Json" -c "Z:\Stammdaten-LB.json" -o Z:\

Wobei:
Kassa-LB1_DEP_Export_Gesamt.Json :  der DEP Export ist
Stammdaten-LB.json : die Datei mit dem AES Key, der Seriennummer des Zertifikates, der Signatur ist
output.txt  : die Datei ist in der das Prüfergebniss gespeichert werden soll.

Sorry - aber wahrscheinlich bin ich einfach zu blöd um das zu kapieren ...

Danke für die Hilfe.

**Comment by Skerge12** [comment]
Hat sich erledigt.
Ich habe es doch hinbekommen

Danke !
