### ISSUE TITLE
Prüfwerkzeug "regkassen-verification-depformat-0.5.jar" wirft Exception

### ISSUE THREAD

**Issue by avosskoetter** [a-sit-plus/at-registrierkassen-mustercode#45]
Leider läuft bei mir das Prüfwerkzeug "regkassen-verification-depformat-0.5.jar" nicht und wirft eine Exception:

D:\Dev\Projekte\RKSV>c:\PROGRA~2\java\jre7\bin\java -jar .\regkassen-verificatio
n-depformat-0.5.jar -i .\DEP-20160310-140911001-123456-1AB8B0.txt -k .\AES-VEC-F
SC-AT-123456-1AB8B0.txt
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cl
i/ParseException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.getMainMethod(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseExcepti
on
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more

Auch wenn ich das Java-Paket "commons-cli-1.3.1.jar" im LIB-Verzeichnis der Java Installation ablege, kommt es zur o.g. Exception.

Was fehlt fehlt?

**Comment by avosskoetter** [comment]
Das Problem hat sich erledigt, wenn man das Paket am richtigen Ort aufruft, läuft das Programm auch.

**Comment by asitplus-pteufl** [comment]
Ok, dann schließe ich das. Noch als Hinweis. Prüftool 0.6. wird Anfang nächste Woche zur Verfügung stehen, auch wichtige Basistestfälle für die Kassen. AB Prüftool Version 0.7. kann dann auch die Abdeckung der Testfälle geprüft werden.
