### ISSUE TITLE
DEP Prüftool: java.lang.OutOfMemoryError bei ca. 3110 Belegen

### ISSUE THREAD

**Issue by TKast** [a-sit-plus/at-registrierkassen-mustercode#494]
Hat noch jemand das Problem beim Prüfen größerer DEPs ab etwa 3110 Belegen?
Gibt es einen Workaround?

Lustigerweise werden die 3 Result-JSON-Files zu jedem Beleg scheinbar erst am Ende geschrieben statt gleich nach jedem Beleg - da wundert mich ein Speicherüberlauf nicht wirklich.

java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Unknown Source)
        at java.lang.String.<init>(Unknown Source)
        at java.lang.StringBuilder.toString(Unknown Source)
        at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffe
r.java:356)
        at com.fasterxml.jackson.core.io.SegmentedStringWriter.getAndClear(Segme
ntedStringWriter.java:83)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(Object
Writer.java:1007)
        at at.asitplus.regkassen.verification.common.rpc.RKObjectMapper.stringif
y(Unknown Source)
        at at.asitplus.regkassen.verification.common.data.VerificationResult.toS
tring(Unknown Source)
        at java.lang.String.valueOf(Unknown Source)
        at java.lang.StringBuilder.append(Unknown Source)
        at at.asitplus.regkassen.verification.common.BaseVerificationModule.afte
rVerify(Unknown Source)
        at at.asitplus.regkassen.verification.common.BaseVerificationModule.veri
fySingle(Unknown Source)
        at at.asitplus.regkassen.verification.common.BaseVerificationModule.veri
fySingle(Unknown Source)
        at at.asitplus.regkassen.verification.cmdline.Prueftool.checkReceipt(Pru
eftool.java:244)
        at at.asitplus.regkassen.verification.cmdline.CheckDEPExportFormat.perfo
rmSingleReceiptCheck(CheckDEPExportFormat.java:316)
        at at.asitplus.regkassen.verification.cmdline.CheckDEPExportFormat.main(
CheckDEPExportFormat.java:76)

**Comment by ztp-mino** [comment]
Man kann der Java VM mehr Heap Space geben z.B. mit `-Xmx4G`. IIRC habe ich das A-SIT Prüftool schon erfolgreich mit ~50000 Belegen getestet (dauert nur lang). Unser eigenes [Prüftool](https://github.com/ztp-at/RKSV) kommt auch mit DEPs mit ca. 10 Mio. Einträgen zurecht.
