### ISSUE TITLE
Speicherbedarf des Prüftools

### ISSUE THREAD

**Issue by maxp1256** [a-sit-plus/at-registrierkassen-mustercode#619]
Gibt es noch andere, die mit dem Speicherbedarf des Prüftools Probleme haben? Ich wollte soeben die Daten von Februar - Juli prüfen, was zu einem Speicherbedarf des Java-Prozesses von über 5 GB führt. Wie stellt sich der Entwickler die Prüfung eines längeren Zeitraums vor?

Auf Maschinen mit weniger Speicher kommt es zu diversen Fehlermeldungen wie zum Beispiel: 

- OutOfMemoryError: Java heap space
- OutOfMemoryError: GC Overhead Limit exceeded

**Comment by lebail** [comment]
Es wurde ja vor langer Zeit angekündigt, dass dieses Problem in der nächsten Version des Prüftools behoben sein wird (ebenso wie die Sache mit den Nullbelegen bei ausgefallener Sicherheitseinrichtung).

Doch diese Version lässt schon extrem lange auf sich warten.

Ich frage mich ja, womit das BMF eigentlich prüft ...

**Comment by ztp-mino** [comment]
Eventuell klappts ja mit unserem eigenen Prüftool (https://github.com/ztp-at/RKSV). Der Speicherbedarf ist bei großen DEPs zwar auch relativ hoch aber 18.500 Belege sollten eigentlich problemlos funktionieren.

Allerdings habe ich das A-SIT Prüftool auch erfolgreich mit 50.000 Belegen benutzt... Darf ich fragen in was für einer Umgebung Sie das gemacht haben? (Windows/Linux? 32/64 Bit? 32/64 Bit Java? Java Version? etc.)

**Comment by maxp1256** [comment]
Ich werde das andere Tool am Montag testen.

Das offizielle Prüftool lief unter Windows 2008R2 bzw. 2016 mit Java 8 Update 131 (64-bit).
Mittlerweile ist es mit 27.5 GB abgestürzt:

java.lang.OutOfMemoryError
        at java.lang.AbstractStringBuilder.hugeCapacity(Unknown Source)
        at java.lang.AbstractStringBuilder.newCapacity(Unknown Source)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
        at java.lang.AbstractStringBuilder.append(Unknown Source)
        at java.lang.StringBuilder.append(Unknown Source)
        at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:351)
        at com.fasterxml.jackson.core.io.SegmentedStringWriter.getAndClear(SegmentedStringWriter.java:83)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1007)
        at at.asitplus.regkassen.verification.common.rpc.RKObjectMapper.stringify(Unknown Source)
        at at.asitplus.regkassen.verification.cmdline.CheckDEPExportFormat.main(CheckDEPExportFormat.java:109)

**Comment by ztp-mino** [comment]
Hmm, komisch... Icedtea 8 auf einem 64 Bit Linux sollte damit problemlos zurechtkommen...

**Comment by Phoniexk** [comment]
@lebail: Wenn ich es aus anderen Threads, Xing, etc. richtig mitbekommen habe, besitzt das BMF eine Version in der beide Probleme behoben sind... kann mich jetzt aber auch täuschen.

**Comment by maxp1256** [comment]
Das wäre dann aber nicht so ganz die feine Art. Ich sehe es zwar ein, dass das BMF mit einer Version arbeitet, die vielleicht mehr Detaildaten prüfen kann - aber für die Softwarehersteller sollte zumindest eine funktionierende Version zur technischen Prüfung zur Verfügung gestellt werden.

**Comment by Ralf-Friedl** [comment]
Nach meinen Beobachtungen ist der Text zu einem Beleg im DEP normalerweise weniger als 300 Byte, selbst wenn man Werte wie CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-1 verwendet, die vermutlich länger sind als was man in der Praxis verwenden wird, einschließlich Vorspann eyJhbGciOiJFUzI1NiJ9 und alles als BASE64 kodiert. Wenn man noch etwas Overhead einrechnet, sollten es weniger als 400 Byte pro Beleg sein, 25.000 Belege sollten demnach locker in 10MB Speicher passen.
Weiterhin ist für die Prüfung nur der jeweilige Vorbeleg notwendig, im Prinzip könnte man beliebig viele Belege prüfen, ohne dass alle im Hauptspeicher sein müssten.
Es scheint, dass das Prüfprogramm hier einige sehr ineffiziente Operationen mit der Liste der Belege durchführt.

Die einzige Prüfung, für die man alle Vorbelege braucht, ist ob die Belegnummer bereits verwendet wurde, und hier würde es reichen, nur die Belegnummer zu speichern und nicht den ganzen Beleg.

**Comment by ztp-mino** [comment]
Ein paar Probleme mit dieser Rechnung:
* Alle Strings in den Belegen können Unicode Zeichen enthalten. Je nachdem wie die Runtime Strings im Speicher ablegt könnte also ein Zeichen 1-4 Byte brauchen. Im Fall von Java sind es AFAIK 2. Wobei es auch `-XX:+UseCompressedStrings` gibt, wo es dann nur eins ist (sofern das Zeichen so dargestellt werden kann).
* Overhead von Objekten. Je nachdem wie jetzt Belege verarbeitet werden, kann der schon ein Vielfaches sein.
* 25000 Belege brauchen bei mir auf der Platte etwa 7MB, ich vermute mal, dass sie im Speicher 5-10 Mal so viel Platz nehmen (zumindest bei Java).

Sie haben natürlich trotzdem völlig recht, dass es mit ein paar Gigabyte Speicher locker gehen sollte und auch damit, dass man zur Prüfung eines DEPs eigentlich nur die bereits verwendeten Belegnummern die ganze Zeit im Speicher behalten muss.

Ich bin nicht sicher wohin das Prüftool den Speicher frisst. Wenn es schon kein Update gibt, könnte man aber zumindest den Source Code veröffentlichen, damit die Leute sich selbst helfen können...

**Comment by clystron** [comment]
Das Tool dürfte wirklich recht "kurzsichtig" programmiert worden sein was den Resourcenverbrauch angeht.
Das von maxp1256 beschriebene Problem sieht zwar aus wie "zu wenig Speicher", tatsächlich ist es aber so dass hier durch Anhängen an einen StringBuilder eine Zeichenkette mit mehr als 2^31 Zeichen entstehen würde und das geht schlicht und ergreifend nicht. Dieser konkrete Fall ist nicht durch mehr RAM lösbar.

**Comment by Ralf-Friedl** [comment]
Und warum sollte bei den genannten Eingabedaten versucht werden, einen String aufzubauen, der länger als 2GB ist? Windows verwendet normalerweise 2Bytes für Unicode Zeichen. Selbst bei 4Bytes pro Zeichen wären das über 500 Millionen.

Möglicherweise generiert das Tool zuerst alle Prüfberichte, bevor sie in Dateien geschrieben werden. Der letzte Prüfbericht enthält alle 18.500 Belege. Wenn der Speicher nicht freigegeben wird, sind das für alle Belege ca. 18.500^2*300 = ca. 100GB. Vielleicht wird der Speicher auch freigegeben, ist aber wegen Fragmentierung nicht nutzbar. Allein die letzte Datei werden für die Liste schon ca. 18.500 * 300 * 2 = ca. 11MB benötigt (gerechnet mit 300 Zeichen zu 2 Bytes).

Vielleicht kann @maxp1256 feststellen, ob beim Abbruch des Programms überhaupt schon Dateien erstellt wurden, und wenn ja, bis zu welchem Beleg das Programm kommt, bevor es abbricht.

Generell finde ich es sinnvoll, wenn man die erstellten Belege prüfen kann. Andererseits, nachdem ich die Testdaten habe durchlaufen lassen und diese korrekt waren, gehe ich davon aus, dass das Programm auch mit Echtdaten korrekt arbeitet.

**Comment by clystron** [comment]
Sie haben mich falsch verstanden, nicht 2GB sondern 2^31 Zeichen. Das entspricht üblicherweise ca 4GB RAM-Verbrauch da jedes Zeichen standardmässig 2 Byte belegt. Auch mit Fragmentierung o.Ä. hat das nichts zu tun, der AbstractStringBuilder hat ein hartes Limit von 2^31 Zeichen und wirft einen OutOfMemory-Error wenn er dieses Limit überschreiten würde. Aus dem geposteten StackTrace in Verbindung mit dem Sourcecode des Oracle JRE geht klar hervor dass das der Fall ist. Wieso versucht wird einen so langen String zu erzeugen kann ich ad hoc nicht sagen.

Ich bin derselben Meinung dass hier vermutlich alle Ausgaben zuerst im RAM zusammengebaut werden bevor sie in Dateien geschrieben werden.

**Comment by ztp-mino** [comment]
Wieso funktioniert das Ding dann bei mir mit 50000 Belegen? Wenn der StringBuilder das Limit ist sollte das doch bei mir genauso scheitern. Das Limit kommt ja nehm ich an davon, dass ein int (mit dem die Länge gemessen wird) 32 Bits hat.

Das einzige was auffällt ist, dass das Ding ab Beleg 40000 immer wieder hängt. Liegt vielleicht am GC Overhead?

**Comment by clystron** [comment]
Der StackTrace ist wie gesagt ziemlich eindeutig, die Funktion "hugeCapacity" in der der Fehler geworfen wird allokiert keinen Speicher sondern prüft nur ob die gewünschte Länge einen Überlauf produziert (vorzeichenbehaftete 32Bit-Zahl wird negativ). Ich kann hier nur spekulieren dass es mit dem Prüfergebnis zusammenhängt, ev. treten hier sehr "textintensive" Fehler auf.

Ein Performanceinbruch beim Hantieren mit sehr langen Strings/StringBuildern wäre nichts ungewöhnliches, wenn zudem noch ineffizient gearbeitet wird kann der RAM-Umsatz (Menge an allokiertem und wieder freigegebenem RAM) im Vergleich zur schlussendlich produzierten Datenmenge extrem sein. Das ist dann mit sehr viel Arbeit für den GC verbunden.

Ich nehme an es wurde mit der "v"-Option gearbeitet? Dann sollte man eigentlich sehen bei welchem Schritt das Problem auftritt.

**Comment by clystron** [comment]
Wenn ich mir den Demo-Output so anschaue dann hab ich das Feld KNOWN_RECEIPT_IDS im Prüfmodul DEP_UNIQUE_RECEIPT_ID im abschliessenden DEP.json im Verdacht. Dieses Feld enthält alle bekannten Belegnummern und wird pro Beleg zwei mal in das Prüfergebnis eingefügt ("input", "output"). Wenn nun wirklich das ganze DEP.json am Schluss am Stück geschrieben wird kann ich mir sehr gut vorstellen dass das ein Problem abgibt. Ganz grob überschlagen bei 8 Zeichen für die Belegnummer benötigen diese beiden Felder beim 18500. Beleg 296000 Zeichen. Nun wächst die Liste aber pro Beleg also können wir pro Beleg die halbe Länge als Durchschnitt annehmen, also 148000 Zeichen. Das mal 18500 ergibt ~2.7Milliarden Zeichen und würde die maximale Länge sprengen. Wenn ich hier keinen Denkfehler drin habe kann ich mir nicht vorstellen dass das mit 50000 Belegen gehen soll, immer angenommen das ganze File wird zuerst als String zusammengebaut und es gibt keine Längenbegrenzung der Fehler bei der Ausgabe.

**Comment by clystron** [comment]
Zusatzkommentar: Bitte auch berücksichtigen dass ich vom Prüftool für den DEP-Export spreche (regkassen-verification-depformat-1.0.0.jar) und nicht vom Prüftool für Belege (regkassen-verification-receipts-1.0.0.jar). Das Prüftool für Belege erstellt nur viele kleine Dateien, das kommt wohl auch mit 50000 zurecht aber das DEP-Tool erzeugt am Schluss noch eine grosse Datei und die kann wohl problematisch werden.

**Comment by ztp-mino** [comment]
Tatsächlich ist mir das depformat Tool gerade auch abgestürzt (bei etwa 45000 Belegen, anderer Fehler allerdings). Ich bin aber sicher, dass ichs mit diesem DEP einmal zum durchlaufen gebracht hab weil ich das für Geschwindigkeitsvergleiche mit unserem eigenen Prüftool herangezogen habe.

**Comment by ztp-mino** [comment]
Nach ein bisschen herumprobieren kann ich melden, dass ich mich anscheinend geirrt habe. Mit dem 1.0.0er Prüftool hab ichs auch nicht geschafft. Es geht allerdings mit dem 0.7.1er...

**Comment by clystron** [comment]
So passts zusammen, die 0.7.1er erzeugt eine wesentlich weniger grosse DEP.json Datei am Ende, da sind z.B. die Belegnummern-Listen nicht drin.

**Comment by Skerge12** [comment]
Guten Tag allerseits,
bei mir ist es jetzt auch soweit:
Auf meinem Windows10 PC bricht das Prüftool mit der Meldung:

Fatal internal error. Detailed error-stacktrace:
java.lang.OutOfMemoryError: Java heap space
at java.util.Arrays.copyofRange(Unknown Source)
at java.lang.String.<init>(Unknown Source)
at java.lang.StringBuilder.toString(Unknown Source)
at com.fasterxml.jackson.core.util.TextBuffer.contendAsString(TextBuffer.java:356)
at com.fasterxml.jackson.core.io.SegmentedStringWriter.get:AndClear(SegmentedStringWriter.java:83)
at com.fasterxml.jackson.core.databind.Objectwriter.writeValueAsString(Objectwriter.java:1007)
at at.asitplus.regkassen.verification.common.rpc.RKObjectMapper.stringify(Unknown Source)
at at.asitplus.regkassen.verification.cmdline.CheckDEPExportFormat.main.(CheckDEPExportformat.java:109)

Da ich mich mit Java leider NULL auskenne habe ich keine Ahnung wie ich das Prüftool wieder zum Laufen bringen kann und bitte hier um Hilfe.

Ich arbeite mit folgendem Programmaufruf: ...      regkassen-verification-depformat-1.0.0.jar" -v -f -i

>>> So passts zusammen, die 0.7.1er erzeugt eine wesentlich weniger grosse DEP.json Datei am Ende, da >>> sind z.B. die Belegnummern-Listen nicht drin.

Ist das eine neuere Version des Prüftools und wenn ja wo könnte ich die runterladen ?

Danke für die Hilfe.

**Comment by clystron** [comment]
Dieser Fehler kommt wirklich daher dass zu wenig RAM zur Verfügung steht, der Zusatz "Java heap space" und die Tatsache dass der Fehler beim Kopieren eines Arrays passiert ist gibt hier den entsprechenden Hinweis.

Mehr RAM für den Heap (=Speicher in dem die meisten Daten liegen) gibt man java mit dem Parameter -Xmx, z.B. so:

java -Xmx5000M -jar  regkassen-verification-depformat-1.0.0.jar  -v -f -i

Das würde Java 5000MB als maximale Heap-Grösse zusprechen (Zahl willkürlich gewählt), dabei ist zu berücksichtigen dass für alles was deutlich über 2GB geht auf jeden Fall die 64Bit Version verwendet werden muss und natürlich sollte der Arbeitsspeicher auch vorhanden sein...
Für optimale Performance kann man auch die Startgrösse für diesen Speicher angeben, am besten auf den gleichen Wert wie die Endgrösse. Das macht man mit dem Parameter -Xms, also z.B.

java -Xms5000M -Xmx5000M -jar .......

Die Version 0.7.1 ist älter als die 1.0.0, insofern ist die Frage wie sinnvoll deren Verwendung ist.

**Comment by Skerge12** [comment]
Dankeschön :)
