### ISSUE TITLE
Demoprogramm nicht ausführbar

### ISSUE THREAD

**Issue by hg7799** [a-sit-plus/at-registrierkassen-mustercode#72]
Wir versuchen das Programm regkassen-demo-0.6.jar auszuführen (Java 1.8 unter Windows 7)

Anbei das Resultat. Danke für jeden Hinweis!

```
T:\reg-demo>java -jar regkassen-demo-0.6.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
        at javax.crypto.JceSecurityManager.<clinit>(JceSecurityManager.java:65)
        at javax.crypto.Cipher.getConfiguredPermission(Cipher.java:2587)
        at javax.crypto.Cipher.getMaxAllowedKeyLength(Cipher.java:2611)
        at at.asitplus.regkassen.core.base.util.CryptoUtil.isUnlimitedStrengthPolicyAvailable(CryptoUtil.java:88)
        at at.asitplus.regkassen.demo.RKSVCashboxSimulator.main(RKSVCashboxSimulator.java:87)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
        at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:89)
        ... 5 more
Caused by: java.lang.SecurityException: Cannot locate policy or framework files!

        at javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:256)
        at javax.crypto.JceSecurity.access$000(JceSecurity.java:48)
        at javax.crypto.JceSecurity$1.run(JceSecurity.java:81)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:78)
        ... 5 more

**Comment by asitplus-pteufl** [comment]
Bitte Readme zu unlimites strength policies lesen.

**Comment by asitplus-pteufl** [comment]
wenn es Ihnen nur um den output geht, brauchen sie das demo aber nicht ausführen, einfach den BSP Output herunterladen.

**Comment by hg7799** [comment]
Unlimited Strength Policies sind installiert. 

Es geht leider nicht nur um den Output. Wir versuchen die Aufbereitung der Daten unter IOS zu implementieren. AES-CTR wird von der Bibliothek angeboten, ist aber leider sehr 'absturzanfällig'. Alternativ haben wir AES-ECB implementiert, erzeugt jedoch ein anderes Resultat als AES-CTR. Also machen wir etwas falsch. Deshalb die Notwendigkeit, unsere Codierung im Vergleich mit einer gültigen Referenz-Software zu testen. Für jeden Hinweis auf eine Software, mit der wir unsere Codierungen testen oder vergleichen können wäre großartig!

**Comment by asitplus-pteufl** [comment]
Kann sein dass mit der Java Installation etwas nicht stimmt? Verwenden sie es unter OS X (stellt kein Problem dar)? Haben Sie das JDK installiert oder nur die JRE (Frage bezieht sich darauf ob die Policy Files auch in der richtigen Java VM installiert sind)?

**Comment by hg7799** [comment]
Danke für den Hinweis. Unter Mac nun ausführbar, nachdem alle alten JRE entfernt wurden.
