### ISSUE TITLE
Umsatzzähler mit weniger als 8 Bytes

### ISSUE THREAD

**Issue by hummmel** [a-sit-plus/at-registrierkassen-mustercode#76]
In der RKSV ist als Länge des Umsatzzählers 5-8 Bytes vorgegeben. Wir haben 6 Bytes gewählt, weil damit Summen bis zu 2,8 Billionen Euro darstellbar sind (sollte reichen), andererseits die base64-Darstellung in der Signatur nur 8 Zeichen benötigt (bei 8 Bytes wären es 12 Zeichen).

Das Prüftool 0.6 meldet mit diesen Daten aber einen Fehler:
ÜBERPRÜFUNG: "Verschlüsselter Umsatzzähler": FEHLERHAFT
DETAILS: Ergebnis für Umsatzzähler ist nicht korrekt.
STACKTRACE: java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Unknown Source)
	at java.nio.HeapByteBuffer.getLong(Unknown Source)
	at at.asitplus.regkassen.core.base.util.CryptoUtil.decryptTurnOverCounter(CryptoUtil.java:460)
	at at.asitplus.regkassen.core.base.util.CryptoUtil.decryptTurnOverCounter(CryptoUtil.java:398)
	at at.asitplus.regkassen.verification.core.verification.verificationmodules.TurnOverCounterVerificationModule.verify(TurnOverCounterVerificationModule.java:102)
	at at.asitplus.regkassen.verification.core.verification.verificationmodules.DEPExportFormatVerificationModule.verify(DEPExportFormatVerificationModule.java:172)
	at at.asitplus.regkassen.verification.cmdline.CheckDEPExportFormat.main(CheckDEPExportFormat.java:85)

Bitte um Bestätigung, dass der Fehler im Prüftool liegt.

**Comment by asitplus-pteufl** [comment]
Dies ist noch ein Fehler im Prüftool, mit Version 0.7 wird das behoben.

**Comment by hummmel** [comment]
Wir werden mit den Endtests dann auf 0.7 warten, auch um Fehler bei uns ausschließen zu können.
Vielen Dank für die rasche Antwort.
