### ISSUE TITLE
regkassen-verification-depformat-0.6.jar:  java.lang.NullPointerException

### ISSUE THREAD

**Issue by 01af** [a-sit-plus/at-registrierkassen-mustercode#82]
Hallo!

Erstmal: möglicherweise ist es eher ein Problem auf meiner Seite, sonst hätten schon mehr geschrien...

Die "Unlimited Strength Policy" ist installiert , und der **RKSVCashboxSimulator** läuft problemlos.
Möchte ich allerdings den Output der Simulation mit dem tool verifizieren, erhalte ich folgende Fehlermeldung:
```
java  -jar regkassen-verification-depformat-0.6.jar -i ./dep-export.json -c ./cryptographicMaterialContainer.json
Exception in thread "main" java.lang.NullPointerException
	at at.asitplus.regkassen.core.base.util.CashBoxUtils.getQRCodeRepresentationFromJWSCompactRepresentation(CashBoxUtils.java:136)
	at at.asitplus.regkassen.verification.core.verification.verificationmodules.CashBoxIDAndReceiptIdentifierAreUniqueVerificationModule.verify(CashBoxIDAndReceiptIdentifierAreUniqueVerificationModule.java:62)
	at at.asitplus.regkassen.verification.core.verification.verificationmodules.DEPExportFormatVerificationModule.verify(DEPExportFormatVerificationModule.java:139)
	at at.asitplus.regkassen.verification.cmdline.CheckDEPExportFormat.main(CheckDEPExportFormat.java:85)
```

Woran könnte das liegen? Danke schon mal!

```
java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

**Comment by asitplus-pteufl** [comment]
Können sie die Dateien die Sie als Input verwenden (DEP, CryptoContainer) posten, dann kann ich es schnell nachvollziehen. In der nächsten Version des Prüftools werden die Fehler aussagekräftiger.

**Comment by 01af** [comment]
Danke für die schnelle Antwort! 
Wie schon befürchtet war es mein Fehler.
Es war die DEP Datei fehlerhaft. 
Hier der relevante Auszug:

```
...
"Belege-kompakt": [
"eyJhbGciOiJFU...",
"eyJhbGciOiJFU...",
  ]
```
Nach dem letzten Element in der Liste hatte ich fälschlicherweise einen ',' gesetzt.
